//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIMODELO_envases
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Almacen_Articulo
    {
        [Key]
        [Required(ErrorMessage = " El Id es requerido")]
        public int Id_Almacen { get; set; }

        [Key]
        [Required(ErrorMessage = " El Id es requerido")]
        public int Id_Articulo { get; set; }

       
        [Required(ErrorMessage = " La fecha de entrada es requerida")]
        public System.DateTime Fecha_Entrada { get; set; }
        public Nullable<System.DateTime> Fecha_Salida { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
    }
}
