//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIMODELO_envases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ENVASESEntities : DbContext
    {
        public ENVASESEntities()
            : base("name=ENVASESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacen_Articulo> Almacen_Articulo { get; set; }
        public virtual DbSet<Almacene> Almacenes { get; set; }
        public virtual DbSet<Articulo> Articulos { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Empleo> Empleos { get; set; }
        public virtual DbSet<vista_empleados> vista_empleados { get; set; }
    
        public virtual ObjectResult<proc_Almacen_Articulo_Result> proc_Almacen_Articulo(Nullable<int> id_Almacen)
        {
            var id_AlmacenParameter = id_Almacen.HasValue ?
                new ObjectParameter("Id_Almacen", id_Almacen) :
                new ObjectParameter("Id_Almacen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Almacen_Articulo_Result>("proc_Almacen_Articulo", id_AlmacenParameter);
        }
    
        public virtual ObjectResult<proc_empleados_Result> proc_empleados(string nombre_Empleado)
        {
            var nombre_EmpleadoParameter = nombre_Empleado != null ?
                new ObjectParameter("Nombre_Empleado", nombre_Empleado) :
                new ObjectParameter("Nombre_Empleado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_empleados_Result>("proc_empleados", nombre_EmpleadoParameter);
        }
    }
}
